# Generated by Django 5.2.5 on 2025-11-14 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dashboardpermission'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
