# Generated by Django 5.2.4 on 2025-09-29 20:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_product_in_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncompleteOrderAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_incomplete_orders', models.PositiveIntegerField(default=0)),
                ('abandoned_orders', models.PositiveIntegerField(default=0)),
                ('converted_orders', models.PositiveIntegerField(default=0)),
                ('expired_orders', models.PositiveIntegerField(default=0)),
                ('recovery_emails_sent', models.PositiveIntegerField(default=0)),
                ('recovery_success_count', models.PositiveIntegerField(default=0)),
                ('total_lost_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recovered_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recovery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IncompleteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomplete_order_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('is_guest_order', models.BooleanField(default=False)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('abandoned', 'Abandoned'), ('payment_failed', 'Payment Failed'), ('payment_pending', 'Payment Pending'), ('expired', 'Expired'), ('converted', 'Converted to Order')], default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('recovery_attempts', models.PositiveIntegerField(default=0)),
                ('last_recovery_attempt', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer_url', models.URLField(blank=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('abandonment_reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abandoned_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('converted_order_id', models.CharField(blank=True, max_length=50)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomplete_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncompleteOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('abandoned', 'Abandoned'), ('recovery_sent', 'Recovery Email Sent'), ('recovered', 'Customer Returned'), ('converted', 'Converted to Order'), ('expired', 'Expired'), ('deleted', 'Deleted')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('created_by_system', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incomplete_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='incomplete_orders.incompleteorder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Incomplete Order Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncompleteOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_sku', models.CharField(blank=True, max_length=100)),
                ('variant_name', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incomplete_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='incomplete_orders.incompleteorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='IncompleteShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incomplete_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='incomplete_orders.incompleteorder')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('abandoned_cart', 'Abandoned Cart'), ('payment_reminder', 'Payment Reminder'), ('final_reminder', 'Final Reminder'), ('discount_offer', 'Discount Offer')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('opened', models.BooleanField(default=False)),
                ('clicked', models.BooleanField(default=False)),
                ('responded', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('discount_code', models.CharField(blank=True, max_length=50)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('incomplete_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_emails', to='incomplete_orders.incompleteorder')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incompleteorder',
            index=models.Index(fields=['user', '-created_at'], name='incomplete__user_id_31e80c_idx'),
        ),
        migrations.AddIndex(
            model_name='incompleteorder',
            index=models.Index(fields=['status'], name='incomplete__status_b2e763_idx'),
        ),
        migrations.AddIndex(
            model_name='incompleteorder',
            index=models.Index(fields=['session_id'], name='incomplete__session_2f49e0_idx'),
        ),
        migrations.AddIndex(
            model_name='incompleteorder',
            index=models.Index(fields=['expires_at'], name='incomplete__expires_70f9a0_idx'),
        ),
    ]
