# Generated by Django 5.2.5 on 2025-10-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='allow_comments',
        ),
        migrations.DeleteModel(
            name='PageComment',
        ),
    ]
