# Generated by Django 5.2.5 on 2025-10-29 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Setting',
                'verbose_name_plural': 'Contact Settings',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person contacting', max_length=100)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('subject', models.CharField(blank=True, help_text='Subject of the inquiry', max_length=200)),
                ('message', models.TextField(help_text='Contact message')),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment (max 10MB)', null=True, upload_to='contact_attachments/%Y/%m/')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('resolved', 'Resolved'), ('spam', 'Spam')], default='new', help_text='Current status of the contact', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the submitter', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin reference')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replied_at', models.DateTimeField(blank=True, help_text='When a reply was sent', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Admin user assigned to handle this contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_app_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='contact.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Activity',
                'verbose_name_plural': 'Contact Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['status', '-submitted_at'], name='contact_con_status_f54a45_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['priority', '-submitted_at'], name='contact_con_priorit_59f1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email', '-submitted_at'], name='contact_con_email_bd0741_idx'),
        ),
    ]
