# Generated by Django 5.2.4 on 2025-10-27 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_emailconfiguration_emailtemplate_emaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('phone', 'Phone Number'), ('ip', 'IP Address')], help_text='Type of block: phone number or IP address', max_length=10)),
                ('value', models.CharField(help_text='Phone number or IP address to block', max_length=255)),
                ('reason', models.CharField(choices=[('fraud', 'Fraud Detection'), ('spam', 'Spam/Abuse'), ('fake_order', 'Fake Orders'), ('payment_issue', 'Payment Issues'), ('harassment', 'Harassment'), ('policy_violation', 'Policy Violation'), ('manual', 'Manual Block'), ('other', 'Other')], default='manual', help_text='Reason for blocking this item', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about why this was blocked')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this block is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_count', models.PositiveIntegerField(default=0, help_text='Number of times this block has been triggered')),
                ('last_triggered', models.DateTimeField(blank=True, help_text='Last time this block was triggered', null=True)),
                ('blocked_by', models.ForeignKey(blank=True, help_text='Admin user who created this block', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Block List Entry',
                'verbose_name_plural': 'Block List Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['block_type', 'value'], name='dashboard_b_block_t_b34223_idx'), models.Index(fields=['is_active', '-created_at'], name='dashboard_b_is_acti_981190_idx'), models.Index(fields=['reason', '-created_at'], name='dashboard_b_reason_7a7bc2_idx')],
                'unique_together': {('block_type', 'value')},
            },
        ),
    ]
