# Generated by Django 5.2.5 on 2025-11-10 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_root_path', models.CharField(default='backups_storage', help_text='Root directory for storing backups', max_length=500)),
                ('max_backup_size', models.BigIntegerField(default=10737418240, help_text='Maximum backup size in bytes')),
                ('default_retention_days', models.IntegerField(default=30, help_text='Default retention period in days')),
                ('auto_cleanup_enabled', models.BooleanField(default=True, help_text='Automatically cleanup old backups')),
                ('chunk_size', models.IntegerField(default=1048576, help_text='File processing chunk size in bytes')),
                ('max_concurrent_operations', models.IntegerField(default=3, help_text='Maximum concurrent backup/restore operations')),
                ('encrypt_backups', models.BooleanField(default=False, help_text='Encrypt backup files')),
                ('encryption_key', models.CharField(blank=True, help_text='Encryption key (base64 encoded)', max_length=500)),
                ('email_notifications', models.BooleanField(default=True, help_text='Send email notifications for backup events')),
                ('notification_emails', models.TextField(blank=True, help_text='Comma-separated list of email addresses')),
                ('verify_backup_integrity', models.BooleanField(default=True, help_text='Verify backup file integrity using checksums')),
                ('create_pre_restore_backup', models.BooleanField(default=True, help_text='Create backup before restore operations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Settings',
                'verbose_name_plural': 'Backup Settings',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this backup', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes')),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup (Database + Media)'), ('database', 'Database Only'), ('media', 'Media Files Only')], default='full', max_length=20)),
                ('include_media', models.BooleanField(default=True, help_text='Include media files in backup')),
                ('include_staticfiles', models.BooleanField(default=False, help_text='Include static files in backup')),
                ('compress_backup', models.BooleanField(default=True, help_text='Compress backup files')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('current_operation', models.CharField(blank=True, help_text='Current backup operation', max_length=200)),
                ('backup_path', models.CharField(blank=True, help_text='Path to backup file/directory', max_length=500)),
                ('backup_size', models.BigIntegerField(default=0, help_text='Total backup size in bytes')),
                ('compressed_size', models.BigIntegerField(default=0, help_text='Compressed backup size in bytes')),
                ('database_name', models.CharField(blank=True, max_length=100)),
                ('django_version', models.CharField(blank=True, max_length=50)),
                ('python_version', models.CharField(blank=True, max_length=50)),
                ('total_files', models.IntegerField(default=0, help_text='Total number of files in backup')),
                ('total_tables', models.IntegerField(default=0, help_text='Total number of database tables')),
                ('total_records', models.BigIntegerField(default=0, help_text='Total number of database records')),
                ('preserve_foreign_keys', models.BooleanField(default=True, help_text='Preserve foreign key relationships')),
                ('backup_order', models.JSONField(default=list, help_text='Order of model backup for foreign key safety')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if backup failed')),
                ('warnings', models.JSONField(default=list, help_text='List of warnings during backup')),
                ('is_restorable', models.BooleanField(default=True, help_text='Whether this backup can be restored')),
                ('restore_notes', models.TextField(blank=True, help_text='Notes about restoration process')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('original_path', models.CharField(help_text='Original file path', max_length=500)),
                ('backup_path', models.CharField(help_text='Path in backup', max_length=500)),
                ('file_type', models.CharField(choices=[('database', 'Database Dump'), ('media', 'Media File'), ('static', 'Static File'), ('fixture', 'Django Fixture'), ('config', 'Configuration File'), ('log', 'Log File')], max_length=20)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 checksum', max_length=64)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, help_text='Django model name for database files', max_length=100)),
                ('app_label', models.CharField(blank=True, help_text='Django app label', max_length=100)),
                ('record_count', models.IntegerField(default=0, help_text='Number of records for database dumps')),
                ('backed_up_at', models.DateTimeField(auto_now_add=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('compression_used', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether file integrity is verified')),
                ('verification_error', models.TextField(blank=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_files', to='backups.backup')),
            ],
            options={
                'ordering': ['file_type', 'filename'],
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('operation', models.CharField(blank=True, help_text='Current operation being logged', max_length=200)),
                ('step_number', models.IntegerField(default=0, help_text='Step number in backup process')),
                ('total_steps', models.IntegerField(default=0, help_text='Total steps in backup process')),
                ('extra_data', models.JSONField(default=dict, help_text='Additional contextual data')),
                ('exception_info', models.TextField(blank=True, help_text='Exception traceback if applicable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='backups.backup')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupRestore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restore_mode', models.CharField(choices=[('full', 'Full Restore (Replace All Data)'), ('selective', 'Selective Restore'), ('merge', 'Merge with Existing Data')], default='full', max_length=20)),
                ('restore_database', models.BooleanField(default=True)),
                ('restore_media', models.BooleanField(default=True)),
                ('restore_staticfiles', models.BooleanField(default=False)),
                ('selected_models', models.JSONField(default=list, help_text='List of models to restore')),
                ('exclude_models', models.JSONField(default=list, help_text='List of models to exclude')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partial', 'Partially Completed')], default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('current_operation', models.CharField(blank=True, max_length=200)),
                ('restored_files', models.IntegerField(default=0)),
                ('restored_records', models.BigIntegerField(default=0)),
                ('skipped_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
                ('warnings', models.JSONField(default=list)),
                ('restore_notes', models.TextField(blank=True)),
                ('rollback_available', models.BooleanField(default=False, help_text='Whether rollback is possible')),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_operations', to='backups.backup')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_restores', to=settings.AUTH_USER_MODEL)),
                ('pre_restore_backup', models.ForeignKey(blank=True, help_text='Backup created before restore operation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_restore_for', to='backups.backup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('manual', 'Manual Only'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom Cron')], default='manual', max_length=20)),
                ('cron_expression', models.CharField(blank=True, help_text='Custom cron expression', max_length=100)),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup (Database + Media)'), ('database', 'Database Only'), ('media', 'Media Files Only')], default='full', max_length=20)),
                ('include_media', models.BooleanField(default=True)),
                ('include_staticfiles', models.BooleanField(default=False)),
                ('compress_backup', models.BooleanField(default=True)),
                ('max_backups_to_keep', models.IntegerField(default=10, help_text='Maximum number of backups to keep')),
                ('delete_old_backups', models.BooleanField(default=True, help_text='Automatically delete old backups')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('last_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_by', to='backups.backup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['status', '-created_at'], name='backups_bac_status_96f217_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['backup_type', '-created_at'], name='backups_bac_backup__6d0183_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['created_by', '-created_at'], name='backups_bac_created_aebaf9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='backupfile',
            unique_together={('backup', 'original_path')},
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['backup', 'level'], name='backups_bac_backup__592bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['backup', 'created_at'], name='backups_bac_backup__8b7e32_idx'),
        ),
    ]
