# Generated by Django 5.2.4 on 2025-11-17 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('backup_type', models.CharField(choices=[('database', 'Database Only'), ('media', 'Media Files Only'), ('full', 'Full Backup (Database + Media)')], max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('hour', models.IntegerField(default=2, help_text='Hour of the day (0-23)')),
                ('minute', models.IntegerField(default=0, help_text='Minute of the hour (0-59)')),
                ('day_of_week', models.IntegerField(blank=True, help_text='Day of week for weekly backups (0-6, Monday=0)', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month for monthly backups (1-31)', null=True)),
                ('retention_days', models.IntegerField(default=30, help_text='Days to keep backups')),
                ('max_backups', models.IntegerField(default=10, help_text='Maximum number of backups to keep')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Backup Schedule',
                'verbose_name_plural': 'Backup Schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Backup name/description', max_length=255)),
                ('backup_type', models.CharField(choices=[('database', 'Database Only'), ('media', 'Media Files Only'), ('full', 'Full Backup (Database + Media)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('completed', 'Completed'), ('failed', 'Failed'), ('restoring', 'Restoring'), ('restored', 'Restored')], default='pending', max_length=20)),
                ('database_file', models.CharField(blank=True, max_length=500, null=True)),
                ('media_file', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('database_size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('media_size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('total_size', models.BigIntegerField(default=0, help_text='Total size in bytes')),
                ('file_count', models.IntegerField(default=0, help_text='Number of files in backup')),
                ('compression_level', models.IntegerField(default=6)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('last_restored_at', models.DateTimeField(blank=True, null=True)),
                ('restoration_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restore_type', models.CharField(choices=[('database', 'Database Only'), ('media', 'Media Files Only'), ('full', 'Full Backup (Database + Media)')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('validation_passed', models.BooleanField(default=False)),
                ('validation_notes', models.TextField(blank=True, null=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_logs', to='backups.backup')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restore Log',
                'verbose_name_plural': 'Restore Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
