# Generated by Django 5.2.5 on 2025-11-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or notes', null=True),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
