# Generated by Django 5.2.5 on 2025-09-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
    ]
