# Generated by Django 5.2.4 on 2025-10-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_checkoutcustomization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Brand Store', max_length=200)),
                ('site_tagline', models.CharField(default='Your one-stop shop for quality products', max_length=300)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site_logos/')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='site_favicons/')),
                ('contact_phone', models.CharField(default='+1 123-456-7890', max_length=20)),
                ('contact_email', models.EmailField(default='contact@mybrandstore.com', max_length=254)),
                ('contact_address', models.TextField(default='123 Main Street, City, State 12345, Country')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='footer_logos/')),
                ('footer_short_text', models.TextField(default='Brief description about your store that appears in the footer')),
                ('facebook_link', models.URLField(blank=True, help_text='Facebook page URL', null=True)),
                ('youtube_link', models.URLField(blank=True, help_text='YouTube channel URL', null=True)),
                ('quick_links_title', models.CharField(default='Quick Links', max_length=100)),
                ('customer_service_title', models.CharField(default='Customer Service', max_length=100)),
                ('home_text', models.CharField(default='Home', max_length=50)),
                ('home_url', models.CharField(default='/', max_length=200)),
                ('products_text', models.CharField(default='Products', max_length=50)),
                ('products_url', models.CharField(default='/products', max_length=200)),
                ('categories_text', models.CharField(default='Categories', max_length=50)),
                ('categories_url', models.CharField(default='/categories', max_length=200)),
                ('about_text', models.CharField(default='About Us', max_length=50)),
                ('about_url', models.CharField(default='/about', max_length=200)),
                ('contact_text', models.CharField(default='Contact', max_length=50)),
                ('contact_url', models.CharField(default='/contact', max_length=200)),
                ('track_order_text', models.CharField(default='Track Order', max_length=50)),
                ('track_order_url', models.CharField(default='/track-order', max_length=200)),
                ('return_policy_text', models.CharField(default='Return Policy', max_length=50)),
                ('return_policy_url', models.CharField(default='/return-policy', max_length=200)),
                ('shipping_info_text', models.CharField(default='Shipping Info', max_length=50)),
                ('shipping_info_url', models.CharField(default='/shipping-info', max_length=200)),
                ('fraud_checker_text', models.CharField(default='Fraud Checker', max_length=50)),
                ('fraud_checker_url', models.CharField(default='/fraud-checker', max_length=200)),
                ('faq_text', models.CharField(default='FAQ', max_length=50)),
                ('faq_url', models.CharField(default='/faq', max_length=200)),
                ('copyright_text', models.CharField(default='© 2024 My Brand Store. All rights reserved.', max_length=200)),
                ('why_shop_section_title', models.CharField(default='Why Shop With Us?', max_length=200)),
                ('feature1_title', models.CharField(default='Fast Delivery', max_length=100)),
                ('feature1_subtitle', models.CharField(default='Quick & reliable shipping', max_length=200)),
                ('feature2_title', models.CharField(default='Quality Products', max_length=100)),
                ('feature2_subtitle', models.CharField(default='Premium quality guaranteed', max_length=200)),
                ('feature3_title', models.CharField(default='24/7 Support', max_length=100)),
                ('feature3_subtitle', models.CharField(default='Round the clock assistance', max_length=200)),
                ('feature4_title', models.CharField(default='Secure Payment', max_length=100)),
                ('feature4_subtitle', models.CharField(default='Safe & secure transactions', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
