# Generated by Django 5.2.4 on 2025-10-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_logo',
            field=models.CharField(blank=True, help_text='Path to footer logo image (e.g., media/logos/footer-logo.png)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_favicon',
            field=models.CharField(blank=True, help_text='Path to favicon image (e.g., media/icons/favicon.ico)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo',
            field=models.CharField(blank=True, help_text='Path to site logo image (e.g., media/logos/site-logo.png)', max_length=500, null=True),
        ),
    ]
