# Generated by Django 5.2.4 on 2025-10-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_sitesettings_footer_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_pixel_code', models.TextField(blank=True, help_text='Meta Pixel code for Facebook advertising and analytics', null=True)),
                ('meta_pixel_enabled', models.BooleanField(default=False)),
                ('google_analytics_code', models.TextField(blank=True, help_text='Google Analytics tracking code (GA4 or Universal Analytics)', null=True)),
                ('google_analytics_measurement_id', models.CharField(blank=True, help_text='Google Analytics Measurement ID (e.g., G-XXXXXXXXXX)', max_length=50, null=True)),
                ('google_analytics_enabled', models.BooleanField(default=False)),
                ('google_search_console_code', models.CharField(blank=True, help_text='Google Search Console verification meta tag content', max_length=100, null=True)),
                ('google_search_console_enabled', models.BooleanField(default=False)),
                ('bing_webmaster_code', models.CharField(blank=True, help_text='Bing Webmaster Tools verification meta tag content', max_length=100, null=True)),
                ('bing_webmaster_enabled', models.BooleanField(default=False)),
                ('yandex_verification_code', models.CharField(blank=True, help_text='Yandex Webmaster verification meta tag content', max_length=100, null=True)),
                ('yandex_verification_enabled', models.BooleanField(default=False)),
                ('header_scripts', models.TextField(blank=True, help_text='Custom scripts to be added in the <head> section', null=True)),
                ('footer_scripts', models.TextField(blank=True, help_text='Custom scripts to be added before closing </body> tag', null=True)),
                ('gtm_container_id', models.CharField(blank=True, help_text='Google Tag Manager Container ID (e.g., GTM-XXXXXXX)', max_length=20, null=True)),
                ('gtm_enabled', models.BooleanField(default=False)),
                ('hotjar_site_id', models.CharField(blank=True, help_text='Hotjar Site ID for heatmaps and user behavior analytics', max_length=20, null=True)),
                ('hotjar_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration Settings',
                'verbose_name_plural': 'Integration Settings',
            },
        ),
    ]
