# Generated by Django 5.2.4 on 2025-11-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_integrationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to Our Store', help_text='Main headline for the hero slide', max_length=200)),
                ('subtitle', models.CharField(default='Discover amazing products at unbeatable prices', help_text='Supporting text below the main headline', max_length=300)),
                ('desktop_image', models.CharField(blank=True, help_text='Path to desktop hero image (e.g., media/hero/desktop-hero-1.jpg) - Recommended size: 1920x600px', max_length=500, null=True)),
                ('mobile_image', models.CharField(blank=True, help_text='Path to mobile hero image (e.g., media/hero/mobile-hero-1.jpg) - Recommended size: 800x600px', max_length=500, null=True)),
                ('primary_button_text', models.CharField(default='Shop Now', help_text='Text for the primary action button', max_length=100)),
                ('primary_button_url', models.CharField(default='/products/', help_text='URL for the primary button (e.g., /products/ or external URL)', max_length=200)),
                ('secondary_button_text', models.CharField(default='Browse Categories', help_text='Text for the secondary action button', max_length=100)),
                ('secondary_button_url', models.CharField(default='/categories/', help_text='URL for the secondary button (e.g., /categories/ or external URL)', max_length=200)),
                ('text_color', models.CharField(default='#ffffff', help_text='Text color for title and subtitle (hex color code)', max_length=7)),
                ('text_shadow', models.BooleanField(default=True, help_text='Add text shadow for better readability over images')),
                ('background_color', models.CharField(default='#930000', help_text='Background color when no image is available (hex color code)', max_length=7)),
                ('background_gradient', models.CharField(default='linear-gradient(135deg, #930000, #7a0000)', help_text='CSS gradient for background (overrides background_color)', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Order in which this slide appears (1 = first, 2 = second, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this hero slide is active and should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Content',
                'verbose_name_plural': 'Hero Content',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
