# Generated by Django 5.2.4 on 2025-11-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_herocontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_time_max',
            field=models.PositiveIntegerField(default=7, help_text='Maximum delivery time in business days'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_time_min',
            field=models.PositiveIntegerField(default=3, help_text='Minimum delivery time in business days'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='express_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=9.99, help_text='Express shipping cost', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum order amount for free shipping', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='processing_time_max',
            field=models.PositiveIntegerField(default=2, help_text='Maximum processing time in business days'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='processing_time_min',
            field=models.PositiveIntegerField(default=1, help_text='Minimum processing time in business days'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='refund_processing_days_max',
            field=models.PositiveIntegerField(default=10, help_text='Maximum refund processing time in business days'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='refund_processing_days_min',
            field=models.PositiveIntegerField(default=5, help_text='Minimum refund processing time in business days'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='return_policy_content',
            field=models.TextField(default='• 30-day return window from delivery date\n• Items must be in original condition\n• Free return shipping on defective items\n• Refunds processed within 5-10 business days\n• Original packaging required for returns\n• Contact customer service to initiate returns', help_text='Return policy content (supports HTML and line breaks)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='return_policy_title',
            field=models.CharField(default='Return Policy', help_text='Title for return policy section', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='return_window_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days customers can return items'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_info_content',
            field=models.TextField(default='• Free standard shipping on orders over $50\n• Express shipping available for $9.99\n• Orders processed within 1-2 business days\n• Delivery time: 3-7 business days\n• Free shipping on all orders within Bangladesh\n• International shipping available to select countries', help_text='Shipping information content (supports HTML and line breaks)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_info_title',
            field=models.CharField(default='Shipping Information', help_text='Title for shipping information section', max_length=200),
        ),
    ]
