# Generated by Django 5.2.4 on 2025-11-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_sitesettings_delivery_time_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='delivery_time_max',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='delivery_time_min',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='express_shipping_cost',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='free_shipping_threshold',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='processing_time_max',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='processing_time_min',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='refund_processing_days_max',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='refund_processing_days_min',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='return_window_days',
        ),
    ]
