# Generated by Django 5.2.5 on 2025-11-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_remove_unused_shipping_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='custom_today_date',
            field=models.DateField(blank=True, help_text="Custom date to use as 'today' for delivery calculations. Leave empty to use current date.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_area_dhaka_label',
            field=models.CharField(default='Inside Dhaka City', help_text='Label for Dhaka city delivery area', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_area_outside_label',
            field=models.CharField(default='Outside Dhaka City', help_text='Label for outside Dhaka delivery area', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_cutoff_time',
            field=models.TimeField(default='16:00', help_text='Orders placed after this time will be processed the next day (24-hour format)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dhaka_delivery_days_max',
            field=models.PositiveIntegerField(default=2, help_text='Maximum delivery days for Dhaka City (days added to processing date)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dhaka_delivery_days_min',
            field=models.PositiveIntegerField(default=1, help_text='Minimum delivery days for Dhaka City (days added to processing date)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='outside_dhaka_delivery_days_max',
            field=models.PositiveIntegerField(default=3, help_text='Maximum delivery days for Outside Dhaka (days added to processing date)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='outside_dhaka_delivery_days_min',
            field=models.PositiveIntegerField(default=1, help_text='Minimum delivery days for Outside Dhaka (days added to processing date)'),
        ),
    ]
