# Generated by Django 5.2.4 on 2025-11-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_sitesettings_custom_today_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steadfast_enabled', models.BooleanField(default=True, help_text='Enable Steadfast courier service')),
                ('steadfast_base_url', models.URLField(default='https://portal.steadfast.com.bd/api/v1', help_text='Steadfast API base URL', max_length=500)),
                ('steadfast_api_key', models.CharField(blank=True, help_text='Steadfast API key from merchant panel', max_length=255, null=True)),
                ('steadfast_secret_key', models.CharField(blank=True, help_text='Steadfast secret key for API authentication', max_length=255, null=True)),
                ('steadfast_merchant_id', models.CharField(blank=True, help_text='Steadfast merchant identifier', max_length=100, null=True)),
                ('steadfast_dhaka_rate', models.DecimalField(decimal_places=2, default=60.0, help_text='Delivery charge for Dhaka city', max_digits=8)),
                ('steadfast_outside_rate', models.DecimalField(decimal_places=2, default=100.0, help_text='Delivery charge for outside Dhaka', max_digits=8)),
                ('pathao_enabled', models.BooleanField(default=False, help_text='Enable Pathao courier service')),
                ('pathao_base_url', models.URLField(default='https://courier-api-sandbox.pathao.com/api/v1', help_text='Pathao API base URL (sandbox or production)', max_length=500)),
                ('pathao_client_id', models.CharField(blank=True, help_text='OAuth client ID from Pathao', max_length=255, null=True)),
                ('pathao_client_secret', models.CharField(blank=True, help_text='OAuth client secret from Pathao', max_length=255, null=True)),
                ('pathao_username', models.CharField(blank=True, help_text='Pathao merchant username', max_length=100, null=True)),
                ('pathao_password', models.CharField(blank=True, help_text='Pathao merchant password', max_length=255, null=True)),
                ('pathao_store_id', models.CharField(blank=True, help_text='Pathao store identifier', max_length=100, null=True)),
                ('redx_enabled', models.BooleanField(default=False, help_text='Enable RedX courier service')),
                ('redx_base_url', models.URLField(default='https://openapi.redx.com.bd/v1.0.0-beta', help_text='RedX API base URL', max_length=500)),
                ('redx_api_token', models.CharField(blank=True, help_text='RedX API token from merchant panel', max_length=255, null=True)),
                ('default_courier', models.CharField(choices=[('steadfast', 'Steadfast'), ('pathao', 'Pathao'), ('redx', 'RedX')], default='steadfast', help_text='Primary courier service for new orders', max_length=20)),
                ('courier_timeout', models.PositiveIntegerField(default=30, help_text='Maximum time to wait for courier API response (seconds)')),
                ('auto_create_parcel', models.BooleanField(default=False, help_text='Automatically create courier parcels when orders are confirmed')),
                ('enable_tracking', models.BooleanField(default=True, help_text='Allow customers to track their orders via courier API')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Courier Settings',
                'verbose_name_plural': 'Courier Settings',
            },
        ),
    ]
