# Generated by Django 5.2.4 on 2025-11-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_couriersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourierSettings',
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='meta_access_token',
            field=models.CharField(blank=True, help_text='Meta Access Token for Conversions API', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='meta_capi_enabled',
            field=models.BooleanField(default=False, help_text='Enable Conversions API'),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='meta_cart_tracking',
            field=models.BooleanField(default=False, help_text='Enable advanced cart tracking'),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='meta_checkout_tracking',
            field=models.BooleanField(default=False, help_text='Enable checkout funnel tracking'),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='meta_hover_tracking',
            field=models.BooleanField(default=False, help_text='Enable element hover tracking'),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='meta_pixel_id',
            field=models.CharField(blank=True, help_text='Meta Pixel ID (e.g., 123456789012345)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='meta_scroll_tracking',
            field=models.BooleanField(default=False, help_text='Enable scroll depth tracking'),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='meta_section_tracking',
            field=models.BooleanField(default=False, help_text='Enable section view tracking'),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='meta_time_tracking',
            field=models.BooleanField(default=False, help_text='Enable time on page tracking'),
        ),
        migrations.AlterField(
            model_name='integrationsettings',
            name='meta_pixel_code',
            field=models.TextField(blank=True, help_text='Meta Pixel code for Facebook advertising and analytics (Legacy)', null=True),
        ),
    ]
