# Generated by Django 5.2.4 on 2025-10-04 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockActivityBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(choices=[('bulk_import', 'Bulk Import'), ('bulk_adjustment', 'Bulk Adjustment'), ('inventory_count', 'Inventory Count'), ('supplier_delivery', 'Supplier Delivery'), ('bulk_transfer', 'Bulk Transfer')], max_length=20)),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('total_activities', models.PositiveIntegerField(default=0)),
                ('completed_activities', models.PositiveIntegerField(default=0)),
                ('failed_activities', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Activity Batch',
                'verbose_name_plural': 'Stock Activity Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('adjustment', 'Stock Adjustment'), ('initial', 'Initial Stock'), ('transfer', 'Stock Transfer'), ('damaged', 'Damaged Stock'), ('expired', 'Expired Stock'), ('returned', 'Customer Return'), ('sold', 'Stock Sold')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('quantity_before', models.IntegerField(help_text='Stock quantity before the activity')),
                ('quantity_changed', models.IntegerField(help_text='Amount added (positive) or removed (negative)')),
                ('quantity_after', models.IntegerField(help_text='Stock quantity after the activity')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit for this activity', max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total cost for this activity', max_digits=10, null=True)),
                ('reason', models.TextField(help_text='Reason for the stock activity')),
                ('reference_number', models.CharField(blank=True, help_text='Reference number (PO, Invoice, etc.)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_date', models.DateTimeField(help_text='When the stock activity actually occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_activities', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_activities', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='inventory.stockactivitybatch')),
            ],
            options={
                'verbose_name': 'Stock Activity',
                'verbose_name_plural': 'Stock Activities',
                'ordering': ['-activity_date', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='inventory_s_content_12b990_idx'), models.Index(fields=['activity_type'], name='inventory_s_activit_6d38db_idx'), models.Index(fields=['created_by'], name='inventory_s_created_63340a_idx'), models.Index(fields=['activity_date'], name='inventory_s_activit_abcf90_idx'), models.Index(fields=['status'], name='inventory_s_status_a9d5cb_idx')],
            },
        ),
    ]
