"""
Django settings for ecommerce_project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-change-me-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'ckeditor',
    'ckeditor_uploader',
    
    # Local apps
    'users.apps.UsersConfig',
    'products.apps.ProductsConfig',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
    'incomplete_orders.apps.IncompleteOrdersConfig',
    'frontend.apps.FrontendConfig',
    'fraud_checker.apps.FraudCheckerConfig',
    'dashboard.apps.DashboardConfig',
    'settings.apps.SettingsConfig',
    'inventory.apps.InventoryConfig',
    'pages.apps.PagesConfig',
    'contact.apps.ContactConfig',
    'backups.apps.BackupsConfig',
    'utils.apps.UtilsConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    # 'django.middleware.cache.UpdateCacheMiddleware',  # Cache middleware (disabled temporarily)
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',  # Moved before custom middleware
    'users.middleware.DashboardPermissionMiddleware',
    'dashboard.middleware.DashboardSecurityMiddleware',  # Enhanced dashboard security
    'dashboard.middleware.DashboardCSRFMiddleware',     # Enhanced CSRF protection
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'incomplete_orders.middleware.CheckoutAbandonmentMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',  # Cache middleware (disabled temporarily)
]

ROOT_URLCONF = 'ecommerce_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'settings.context_processors.site_settings',
                'settings.context_processors.checkout_customization',
                'settings.context_processors.navbar_categories',
                'settings.context_processors.integration_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce_project.wsgi.application'


# MySQL configuration (commented out - install mysqlclient to use)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'manob_bazar',
        'USER': 'root',
        'PASSWORD': 'aminul3065',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        'CONN_MAX_AGE': 600,  # Connection reuse for 10 minutes
    }
}

# Caching Configuration  
USE_REDIS = False  # Set to True when Redis is available

if USE_REDIS:
    # Redis Caching Configuration (Production)
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379/1',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                },
                'PARSER_CLASS': 'redis.connection.HiredisParser',
                'PICKLE_VERSION': -1,
            },
            'KEY_PREFIX': 'ecommerce',
            'TIMEOUT': 300,  # Default cache timeout (5 minutes)
        },
        'sessions': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379/2',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 20,
                },
            },
            'KEY_PREFIX': 'sessions',
            'TIMEOUT': 86400,  # Session cache timeout (1 day)
        },
        'products': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379/3',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 30,
                },
            },
            'KEY_PREFIX': 'products',
            'TIMEOUT': 3600,  # Product cache timeout (1 hour)
        }
    }
else:
    # Database Cache (Development/Fallback)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'cache_table',
            'TIMEOUT': 300,
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            }
        },
        'sessions': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'session_cache_table',
            'TIMEOUT': 86400,
            'OPTIONS': {
                'MAX_ENTRIES': 500,
            }
        },
        'products': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'product_cache_table',
            'TIMEOUT': 3600,
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            }
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
}

# CORS settings (for frontend API consumption)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React default
    "http://127.0.0.1:3000",
    "http://localhost:8080",  # Vue default
    "http://127.0.0.1:8080",
]

CORS_ALLOW_CREDENTIALS = True

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = ''
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Celery settings (for background tasks like email notifications)
CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Dhaka'

# Cache settings - Use Redis if available, otherwise fallback to dummy cache
try:
    import redis
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379/1',
        }
    }
except ImportError:
    # Fallback to dummy cache if Redis is not available
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'ecommerce.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Authentication URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_BROWSE_SHOW_DIRS = True

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 400,
        'width': '100%',
        'extraPlugins': 'codesnippet,widget,lineutils,clipboard,dialog,dialogui',
        'removePlugins': 'elementspath',
        'forcePasteAsPlainText': True,
        'format_tags': 'p;h1;h2;h3;h4;h5;h6;pre;address;div',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Table', 'HorizontalRule', 'SpecialChar'],
            ['Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Undo', 'Redo'],
            ['Source', 'Preview', 'Maximize'],
            ['CodeSnippet'],
        ],
        'codeSnippet_theme': 'monokai_sublime',
        'codeSnippet_languages': {
            'python': 'Python',
            'javascript': 'JavaScript',
            'css': 'CSS',
            'html': 'HTML',
            'sql': 'SQL',
            'json': 'JSON',
        },
    },
    'pages': {
        'toolbar': 'full',
        'height': 500,
        'width': '100%',
        'extraPlugins': 'codesnippet,widget,lineutils,clipboard,dialog,dialogui,image2,uploadimage',
        'removePlugins': 'elementspath',
        'allowedContent': True,
        'format_tags': 'p;h1;h2;h3;h4;h5;h6;pre;address;div',
        'toolbar_Full': [
            ['Source', 'Preview', 'Templates', 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', 'Undo', 'Redo'],
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', 'Outdent', 'Indent', 'Blockquote', 'CreateDiv'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Table', 'HorizontalRule', 'SpecialChar', 'PageBreak', 'Iframe'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'ShowBlocks'],
            ['CodeSnippet'],
        ],
        'stylesSet': [
            {'name': 'Lead Paragraph', 'element': 'p', 'attributes': {'class': 'lead'}},
            {'name': 'Info Box', 'element': 'div', 'attributes': {'class': 'alert alert-info'}},
            {'name': 'Warning Box', 'element': 'div', 'attributes': {'class': 'alert alert-warning'}},
            {'name': 'Success Box', 'element': 'div', 'attributes': {'class': 'alert alert-success'}},
            {'name': 'Danger Box', 'element': 'div', 'attributes': {'class': 'alert alert-danger'}},
            {'name': 'Button Primary', 'element': 'a', 'attributes': {'class': 'btn btn-primary'}},
            {'name': 'Button Secondary', 'element': 'a', 'attributes': {'class': 'btn btn-secondary'}},
        ],
        'codeSnippet_theme': 'monokai_sublime',
    }
}

# Site configuration
SITE_URL = 'http://127.0.0.1:8000'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'users.authentication.EmailVerificationBackend',
    'django.contrib.auth.backends.ModelBackend',  # Fallback for superusers and admin
]

# reCAPTCHA Settings
# For demonstration purposes - you should replace these with your actual reCAPTCHA keys
# Get your keys from: https://www.google.com/recaptcha/admin/create
RECAPTCHA_SITE_KEY = '6LfaffsrAAAAAFD2-bNrYWkEp2D2esUfmDf1l4TA'
RECAPTCHA_SECRET_KEY = None  # Set this in your .env file for production

# For development/demonstration - bypass reCAPTCHA verification if no secret key is set
RECAPTCHA_BYPASS_FOR_DEMO = True

# Backup System Settings
BACKUP_DIRECTORY = 'backups_storage/'
BACKUP_RETENTION_DAYS = 30
BACKUP_AUTO_CLEANUP = True

# MySQL Backup Settings
BACKUP_MYSQL_PATH = 'mysqldump'
BACKUP_MYSQL_HOST = '127.0.0.1'
BACKUP_MYSQL_PORT = 3306
BACKUP_MYSQL_USER = 'root'
BACKUP_MYSQL_PASSWORD = 'aminul3065'
BACKUP_MYSQL_DATABASE = 'manob_bazar'

# Backup Compression Settings
BACKUP_COMPRESSION_LEVEL = 6

# Backup Notification Settings
BACKUP_EMAIL_NOTIFICATIONS = False
BACKUP_NOTIFICATION_EMAIL = ''

# IP Detection Settings
# Force detection of public IP addresses for order tracking
# Set to True in production to capture real customer IP addresses
FORCE_PUBLIC_IP_DETECTION = True

# ==============================
# DASHBOARD SECURITY SETTINGS
# ==============================

# Dashboard session timeout in minutes (default: 30 minutes)
DASHBOARD_SESSION_TIMEOUT = 30

# IP address validation for dashboard sessions (set to True in production)
DASHBOARD_VALIDATE_IP = False

# User agent validation for dashboard sessions
DASHBOARD_VALIDATE_USER_AGENT = False

# Session configuration with caching
if USE_REDIS:
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'sessions'
else:
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Database only for development
SESSION_COOKIE_SECURE = False  # Set to True with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 60 * 60 * 8  # 8 hours default session age
SESSION_SAVE_EVERY_REQUEST = True

# CSRF security settings
CSRF_COOKIE_SECURE = False  # Set to True with HTTPS
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Security headers (will be added by middleware for dashboard)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Logging configuration for security events
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'dashboard_security.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'dashboard.views': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'dashboard.middleware': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Cache Framework Configuration
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 300  # 5 minutes default
CACHE_MIDDLEWARE_KEY_PREFIX = 'ecommerce'

# Cache timeout settings for different content types
CACHE_TIMEOUTS = {
    'home_page': 300,       # 5 minutes
    'product_list': 600,    # 10 minutes
    'product_detail': 1800, # 30 minutes
    'category_list': 3600,  # 1 hour
    'static_pages': 86400,  # 24 hours
}

# Cache keys configuration
CACHE_KEYS = {
    'featured_products': 'featured_products',
    'categories': 'categories_list',
    'hero_slides': 'hero_slides',
    'site_settings': 'site_settings',
    'popular_products': 'popular_products_{category_id}',
    'product_reviews': 'product_reviews_{product_id}',
}


