# Generated by Django 5.2.4 on 2025-11-04 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_coupon_options_coupon_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Email for guest coupon usage', max_length=254),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='guest_phone',
            field=models.CharField(blank=True, help_text='Phone for guest coupon usage', max_length=20),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user', 'order_id'], name='cart_coupon_coupon__88b805_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'guest_email', 'order_id'], name='cart_coupon_coupon__3e30d6_idx'),
        ),
    ]
