# Generated by Django 5.2.4 on 2025-11-15 18:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_directory', models.CharField(default='backups/', help_text='Directory to store backup files', max_length=500)),
                ('max_backup_size', models.BigIntegerField(default=1073741824, help_text='Maximum backup file size in bytes')),
                ('mysql_path', models.CharField(default='mysqldump', help_text='Path to mysqldump executable', max_length=500)),
                ('mysql_host', models.CharField(default='localhost', max_length=255)),
                ('mysql_port', models.PositiveIntegerField(default=3306)),
                ('mysql_user', models.CharField(blank=True, max_length=255)),
                ('mysql_password', models.CharField(blank=True, max_length=255)),
                ('mysql_database', models.CharField(blank=True, max_length=255)),
                ('compression_level', models.PositiveIntegerField(default=6, help_text='Compression level (1-9, 9 = best compression)')),
                ('default_retention_days', models.PositiveIntegerField(default=30, help_text='Default number of days to keep backups')),
                ('auto_cleanup', models.BooleanField(default=True, help_text='Automatically delete old backups')),
                ('email_notifications', models.BooleanField(default=False, help_text='Send email notifications for backup status')),
                ('notification_email', models.EmailField(blank=True, help_text='Email address for notifications', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Settings',
                'verbose_name_plural': 'Backup Settings',
                'db_table': 'backup_settings',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Custom name for the backup', max_length=255)),
                ('backup_type', models.CharField(choices=[('database', 'Database Only'), ('media', 'Media Files Only'), ('full', 'Database + Media Files')], default='full', help_text='Type of backup to create', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current backup status', max_length=20)),
                ('database_file', models.CharField(blank=True, help_text='Path to database backup file', max_length=500, null=True)),
                ('media_file', models.CharField(blank=True, help_text='Path to media backup file', max_length=500, null=True)),
                ('file_size', models.BigIntegerField(default=0, help_text='Total backup size in bytes')),
                ('database_size', models.BigIntegerField(default=0, help_text='Database backup size in bytes')),
                ('media_size', models.BigIntegerField(default=0, help_text='Media backup size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the backup')),
                ('error_message', models.TextField(blank=True, help_text='Error message if backup failed')),
                ('compress', models.BooleanField(default=True, help_text='Whether to compress backup files')),
                ('exclude_logs', models.BooleanField(default=True, help_text='Exclude log files from media backup')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this backup', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Record',
                'verbose_name_plural': 'Backup Records',
                'db_table': 'backup_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('backup_type', models.CharField(choices=[('database', 'Database Only'), ('media', 'Media Files Only'), ('full', 'Database + Media Files')], default='full', max_length=20)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='daily', max_length=20)),
                ('hour', models.PositiveIntegerField(default=2, help_text='Hour of day (0-23)')),
                ('minute', models.PositiveIntegerField(default=0, help_text='Minute (0-59)')),
                ('day_of_week', models.PositiveIntegerField(blank=True, help_text='Day of week for weekly backup (0=Monday, 6=Sunday)', null=True)),
                ('day_of_month', models.PositiveIntegerField(blank=True, help_text='Day of month for monthly backup (1-31)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('compress', models.BooleanField(default=True)),
                ('exclude_logs', models.BooleanField(default=True)),
                ('retention_days', models.PositiveIntegerField(default=30, help_text='Number of days to keep backups (0 = keep forever)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Schedule',
                'verbose_name_plural': 'Backup Schedules',
                'db_table': 'backup_schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Custom name for the restore', max_length=255)),
                ('uploaded_database_file', models.FileField(blank=True, help_text='Uploaded database file for restore', null=True, upload_to='restore_uploads/database/', validators=[django.core.validators.FileExtensionValidator(['sql', 'gz'])])),
                ('uploaded_media_file', models.FileField(blank=True, help_text='Uploaded media file for restore', null=True, upload_to='restore_uploads/media/', validators=[django.core.validators.FileExtensionValidator(['tar', 'gz', 'zip'])])),
                ('restore_type', models.CharField(choices=[('database', 'Database Only'), ('media', 'Media Files Only'), ('full', 'Database + Media Files')], default='full', help_text='Type of restore to perform', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current restore status', max_length=20)),
                ('overwrite_existing', models.BooleanField(default=False, help_text='Overwrite existing data during restore')),
                ('backup_before_restore', models.BooleanField(default=True, help_text='Create backup before performing restore')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the restore')),
                ('error_message', models.TextField(blank=True, help_text='Error message if restore failed')),
                ('backup_record', models.ForeignKey(blank=True, help_text='Associated backup record (if restoring from existing backup)', null=True, on_delete=django.db.models.deletion.CASCADE, to='backup.backuprecord')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who initiated this restore', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pre_restore_backup', models.ForeignKey(blank=True, help_text='Backup created before this restore', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_from', to='backup.backuprecord')),
            ],
            options={
                'verbose_name': 'Restore Record',
                'verbose_name_plural': 'Restore Records',
                'db_table': 'restore_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
