# Generated by Django 5.2.4 on 2025-08-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_guest_email_order_is_guest_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory',
            name='carrier_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='is_customer_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='is_milestone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='is_system_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Order Placed'), ('confirmed', 'Order Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=20),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
