# Generated by Django 5.2.5 on 2025-09-13 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_curier_charge_order_curier_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='partially_ammount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='curier_charge',
            field=models.DecimalField(decimal_places=2, default=110, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
