# Generated by Django 5.2.5 on 2025-09-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_cost_price_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
