# Generated by Django 5.2.4 on 2025-09-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_send_curier'),
        ('orders', '0007_alter_shippingaddress_last_name'),
    ]

    operations = [
    ]
