# Generated by Django 5.2.5 on 2025-09-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_merge_20250919_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='send_curier',
        ),
    ]
