# Generated by Django 5.2.5 on 2025-09-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_send_curier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='curier_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
