# Generated by Django 5.2.5 on 2025-10-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_curier_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bkash_sender_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='bkash_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='nagad_sender_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='nagad_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('bkash', 'bKash'), ('nagad', 'Nagad')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
