# Generated by Django 5.2.5 on 2025-10-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_bkash_sender_number_order_bkash_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready_for_shipped', 'Ready for Shipped'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('partially_returned', 'Partially Returned'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Order Placed'), ('confirmed', 'Order Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('ready_for_shipped', 'Ready for Shipped'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=20),
        ),
    ]
