# Generated by Django 5.2.4 on 2025-10-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status_alter_orderstatushistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_ip',
            field=models.GenericIPAddressField(blank=True, help_text="Customer's IP address when placing order", null=True),
        ),
    ]
