# Generated by Django 5.2.4 on 2025-11-04 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_coupon_options_coupon_created_by_and_more'),
        ('orders', '0013_order_customer_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Coupon code applied to this order', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount from coupon', max_digits=8),
        ),
    ]
