# Generated by Django 5.2.4 on 2025-12-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_coupon_alter_order_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
