# Generated by Django 5.2.4 on 2025-12-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
