# Generated by Django 5.2.4 on 2025-07-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant_image'),
    ]

    operations = [
    ]
