# Generated by Django 5.2.4 on 2025-07-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20250725_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_express_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom express shipping cost for Dhaka (leave blank to use default)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_shipping_dhaka',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom shipping cost for Dhaka (leave blank to use default)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_shipping_outside',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom shipping cost outside Dhaka (leave blank to use default)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_type',
            field=models.CharField(choices=[('free', 'Free Shipping'), ('standard', 'Standard Shipping (Dhaka: 70 Tk, Outside: 120 Tk)'), ('express', 'Express Shipping (Dhaka Only: 150 Tk)')], default='standard', help_text='Select shipping option for this product', max_length=20),
        ),
    ]
