# Generated by Django 5.2.4 on 2025-07-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_custom_express_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_express_shipping',
            field=models.BooleanField(default=False, help_text='Check to enable Express Shipping (Same Day Delivery - Dhaka Only)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='custom_express_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom express shipping cost for Dhaka (leave blank to use default 150 Tk)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='custom_shipping_dhaka',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom shipping cost for Dhaka (leave blank to use default 70 Tk)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='custom_shipping_outside',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom shipping cost outside Dhaka (leave blank to use default 120 Tk)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_type',
            field=models.CharField(choices=[('free', 'Free Shipping'), ('standard', 'Shipping with Charge (Dhaka: 70 Tk, Outside: 120 Tk)')], default='standard', help_text='Select main shipping option: Free OR Shipping with Charge', max_length=20),
        ),
    ]
