# Generated by Django 5.2.4 on 2025-07-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_has_express_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Mark this as the default variant for the product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_express_shipping',
            field=models.BooleanField(default=False, help_text='Check to enable Express Shipping'),
        ),
    ]
