# Generated by Django 5.2.4 on 2025-07-27 19:26

from django.db import migrations


def set_default_variants(apps, schema_editor):
    """Set the first active variant as default for each product that has variants"""
    Product = apps.get_model('products', 'Product')
    ProductVariant = apps.get_model('products', 'ProductVariant')
    
    for product in Product.objects.all():
        # Get the first active variant for this product
        first_variant = ProductVariant.objects.filter(
            product=product, 
            is_active=True
        ).first()
        
        if first_variant and not ProductVariant.objects.filter(
            product=product, 
            is_default=True
        ).exists():
            # Set the first variant as default if no default exists
            first_variant.is_default = True
            first_variant.save()


def reverse_default_variants(apps, schema_editor):
    """Remove default status from all variants"""
    ProductVariant = apps.get_model('products', 'ProductVariant')
    ProductVariant.objects.update(is_default=False)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productvariant_is_default_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_variants, reverse_default_variants),
    ]
