# Generated by Django 5.2.4 on 2025-08-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20250728_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID)'),
        ),
    ]
