# Generated by Django 5.2.4 on 2025-08-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_reviewimage_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
