# Generated by Django 5.2.4 on 2025-08-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='in_stock',
            field=models.BooleanField(default=True, help_text='Indicates if this variant is currently in stock and available for ordering'),
        ),
    ]
