# Generated by Django 5.2.4 on 2025-09-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productvariant_compare_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, help_text='Indicates if this product is currently in stock and available for ordering'),
        ),
    ]
