# Generated by Django 5.2.5 on 2025-10-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(help_text='URL or path to the image file', max_length=500),
        ),
    ]
