# Generated by Django 5.2.5 on 2025-10-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_change_productimage_to_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.URLField(blank=True, help_text='URL or path to the variant image file', max_length=500, null=True),
        ),
    ]
