# Generated by Django 5.2.4 on 2025-10-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_change_variant_image_to_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(help_text='URL or path to the image file', max_length=500),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.CharField(blank=True, help_text='URL or path to the variant image file', max_length=500, null=True),
        ),
    ]
