# Generated by Django 5.2.5 on 2025-10-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_productimage_image_alter_productvariant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.TextField(blank=True, help_text='URL or path to the category image', max_length=500, null=True),
        ),
    ]
