# Generated by Django 5.2.4 on 2025-12-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_change_category_image_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_homepage',
            field=models.BooleanField(default=False, help_text='Show this category products on homepage'),
        ),
    ]
